import Cidade from '#models/cidade'
import { BaseSeeder } from '@adonisjs/lucid/seeders'

export default class extends BaseSeeder {
  async run() {
    await Cidade.createMany([
      { nome: 'Dourados', uf: 'MS' },
      { nome: 'Amambai', uf: 'MS' },
      { nome: 'Antonio João', uf: 'MS' },
      { nome: 'Aral Moreira', uf: 'MS' },
      { nome: 'Bela Vista', uf: 'MS' },
      { nome: 'Caarapó', uf: 'MS' },
      { nome: 'Coronel Sapucaia', uf: 'MS' },
      { nome: 'Douradina', uf: 'MS' },
      { nome: 'Itaporã', uf: 'MS' },
      { nome: 'Juti', uf: 'MS' },
      { nome: 'Laguna', uf: 'MS' },
      { nome: 'Naviraí', uf: 'MS' },
      { nome: 'Nova Alvorada do Sul', uf: 'MS' },
      { nome: 'Rio Brilhante', uf: 'MS' },
      { nome: 'São Gabriel do Oeste', uf: 'MS' },
      { nome: 'Ponta Porã', uf: 'MS' },
      { nome: 'Eldorado', uf: 'MS' },
      { nome: 'Iguatemi', uf: 'MS' },
      { nome: 'Itaquiraí', uf: 'MS' },
      { nome: 'Mundo Novo', uf: 'MS' },
      { nome: 'Altônia', uf: 'PR' },
      { nome: 'Cascavel', uf: 'PR' },
      { nome: 'Cruzeiro do Oeste', uf: 'PR' },
      { nome: 'Goioerê', uf: 'PR' },
      { nome: 'Guaíra', uf: 'PR' },
      { nome: 'Guaraniaçu', uf: 'PR' },
      { nome: 'Icaraíma', uf: 'PR' },
      { nome: 'Iporã', uf: 'PR' },
      { nome: 'Ivaté', uf: 'PR' },
      { nome: 'Marechal Cândido Rondon', uf: 'PR' },
      { nome: 'Mariluz', uf: 'PR' },
      { nome: 'Palotina', uf: 'PR' },
      { nome: 'Santa Helena', uf: 'PR' },
      { nome: 'Santa Tereza do Oeste', uf: 'PR' },
      { nome: 'Umuarama', uf: 'PR' },
      { nome: 'Vera Cruz do Oeste', uf: 'PR' },
      { nome: 'Abadiânia', uf: 'GO' },
      { nome: 'Anápolis', uf: 'GO' },
      { nome: 'Campo Limpo', uf: 'GO' },
      { nome: 'Silvânia', uf: 'GO' },
      { nome: 'Sinop', uf: 'MT' },
      { nome: 'Vera', uf: 'MT' },
      { nome: 'Sorriso', uf: 'MT' },
      { nome: 'Ipiranga do Norte', uf: 'MT' },
      { nome: 'Feliz Natal', uf: 'MT' },
      { nome: 'Colíder', uf: 'MT' },
      { nome: 'Nova Iguaçu', uf: 'RJ' },
      { nome: 'Pedro Juan Caballero', uf: 'PY' },
      { nome: 'Asunción', uf: 'PY' },
      { nome: 'Concepción', uf: 'PY' },
      { nome: 'Horqueta', uf: 'PY' },
      { nome: 'Katueté', uf: 'PY' },
    ])
  }
}